services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.2
    container_name: elasticsearch
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30"
    ports:
      - "9200:9200"
    expose:
      - "9200"
    volumes:
      - noligodata:/usr/share/elasticsearch/data

  webapp:
    build: ./noligomacho
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    expose:
      - "8000"

volumes:
  noligodata:
